### ISSUE TITLE
Android target

### ISSUE THREAD

**Issue by nitrobin** [proletariatgames/unreal.hx#55]
Hi! :) We experimented with UnrealHx under linux and everything was good. But now we are trying to make Android build and we faced a problem.

I'm trying to do HaxePlatformerGame version for Android. https://github.com/nitrobin/HaxePlatformerGame 
https://github.com/nitrobin/unreal.hx
We were able to compile the application into apk-file, but the app crashes immediately at startup:
com.YourCompany.Project-1 / lib / arm / libUE4.so ", RTLD_LAZY) failed: dlopen failed: can not locate symbol" "referenced by" libUE4.so "...

Logs: https://goo.gl/9zVUHF
HaxeModuleRules changes: https://github.com/nitrobin/unreal.hx/blob/android/Haxe/BuildTool/src/HaxeModuleRules.hx#L345

Can anyone help us with it? Any tips?

**Comment by waneck** [comment]
Hey there! Nice to see new targets being added!
The culprit of the load error is a symbol that was not found: `__tls_get_addr` (see https://gist.github.com/nitrobin/10305088f1cef1436067434f2a37eb95#file-haxeplatformergame-log-L79 )

By the looks of it (see https://stackoverflow.com/questions/28198965/how-to-resolve-tls-get-addrglibc-2-3-error-on-compiling-gcc-itself ), this might be due to glibc version issues. It could come from the fact that we are compiling the hxcpp part with the hxcpp build tool, while the unreal part is being compiled with the Unreal Build Tool.

I've seen some of these errors, and I'll be happy to guide you through them. Some starting points would be:

* Get the complete build logs. It would be nice to know whether e.g. hxcpp is being compiled with g++ while unreal is being compiled with clang. This could be an easy fix - by setting hxcpp's environment variables to use clang ( like https://github.com/nitrobin/unreal.hx/blob/android/Haxe/BuildTool/src/HaxeModuleRules.hx#L334 )
* If it's the other way around (hxcpp is using clang, while unreal is using g++ - unlikely), you could try to loose that HXCPP_CLANG define
* Make sure that both unreal and hxcpp are using the same android toolchain
* If that doesn't fix this error, try passing `-verbose` to the unreal build tool, so that we can have a better look at the compilation call differences between hxcpp and UBT

**Comment by nitrobin** [comment]
Hi! Thanks for you quick response!

It looks like first case: libhaxeruntime.a (gcc) + unreal (clang)
I was tried setup CXX and CC variables, but unsuccessfully. As I understand android-toolchain.xml does not use CXX / CC variables. I did patch android-toolchain.xml for clang support and add compiller flags https://gist.github.com/nitrobin/98384f463a4ddb3792e5be9b836c9fcc/revisions?diff=split
I am using most of clang flags from https://github.com/EpicGames/UnrealEngine/tree/4.11/Engine/Source/Programs/UnrealBuildTool/Android
And also change lib linkage: libgnustl_static.a -> libgnustl_shared.so

Still have same error on Nexus 7 (Android 6.0):
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "" referenced by "/data/app/com.YourCompany.Project-1/lib/arm/libUE4.so"...

Full logs from launch panel and apk sample: https://drive.google.com/drive/folders/0B9gz9RtNUdaZTzA4MC1jOXc5MXM
1-first buld with clang
2-build with libgnustl_shared.so and -fsigned-char

Hxcpp patch 'hxcpp\3,3,49\toolchain\android-toolchain.xml':
https://gist.github.com/nitrobin/98384f463a4ddb3792e5be9b836c9fcc
https://gist.github.com/nitrobin/98384f463a4ddb3792e5be9b836c9fcc/revisions?diff=split

Unreal.hx patch 'HaxeModuleRules.hx'
https://github.com/nitrobin/unreal.hx/commit/4797ca1107d8a760470b394db389f19b2e86f4c0

Strange that linker error does not provide symbol name. It is just empty string "".
I am not so experienced in native development. May be is there any tools for shared library diagnostic? Objdump output not helps..
I will try change hxccp linker to ld.gold, but not shure it helps.
It is litle hard for experimenting with compiller flags, rebuild android project on my machine require ~1 hour.. Need more ideas. :)

ps. Looks like UnrealBuildTool.dll was litle outdated. I tried get some ndk data from AndroidToolchain but some method changed in github engine version. I tried link '-net-lib' directly to latest exe instead old dll but it fails (exe uses 4.5 .net). Any way to update? :)

**Comment by waneck** [comment]
That empty symbol name is indeed really weird. I still haven't had time to take a look much deeper into it, I'll try to do it this weekend.

**Comment by waneck** [comment]
I'm curious: What does `ldd -r libUE4.so` / `readelf -d libUE4.so` return? I'm assuming that the project was the Haxe port of the Platformer Game. If so, can you upload it somewhere as well?

**Comment by waneck** [comment]
Oh nevermind, there is the full apk there! Thanks

**Comment by waneck** [comment]
Try taking off that `|| PLATFORM_ANDROID` from https://github.com/proletariatgames/unreal.hx/blob/master/Haxe/Templates/Source/HaxeRuntime/Generated/HaxeInit.cpp#L25

**Comment by nitrobin** [comment]
Thanks! I do changes: "taking off that || PLATFORM_ANDROID"  
It shows spalsh screen now! :D 
http://imgur.com/85f8MkT
I will try to make normal package for app instead "cook on the fly" and will report about my results soon!

**Comment by nitrobin** [comment]
It works! :)
apk+obb here: https://github.com/nitrobin/HaxePlatformerGame/releases/tag/first_android_build https://youtu.be/6AKe4st2wdI
Thanks for your great help @waneck ! :)

We will test this pathces on our project and report status. :)

**Comment by waneck** [comment]
Awesome! If you run into any other issues, feel free to open another issue
