### ISSUE TITLE
HUD-Related Missing Externs?

### ISSUE THREAD

**Issue by jrgalim** [proletariatgames/unreal.hx#70]
Hello, I'm porting the FPS HUD to Haxe, and have run into a few issues:
- The AHUD class seems to be missing the DrawHUD() function.
- UCanvas is missing DrawItem()
- FCanvasTileItem class is missing

Should I be approaching HUD rendering another way?

**Comment by waneck** [comment]
These functions were not autogenerated because they are not UFUNCTIONs on C++. You can still use them - but you have to manually write extra externs. You can read about the `_Extra.hx` externs at https://github.com/proletariatgames/unreal.hx/wiki/Extern-definitions , and you can have a look at some of the externs we've already got at `Haxe/Externs/Common` . Feel free to submit them as a PR once you've got them right.

**Comment by waneck** [comment]
I'm closing this - but feel free to reopen if you think there's an issue
